raspberrypi3: add config for raspberrypi3 and raspberrypi3-64 from meta-raspberrypi
* it's the same as in meta-raspberrypi, but with enabled vc4graphics
  and QT_PACKAGES_ARCH set to ${MACHINE_ARCH} because of bbappend
  we have here

* also without vc4graphics, the gstreamer1.0-plugins-bad bbappend
  in meta-raspberrpi breaks the build due to missing dispmanx
  dependency:

| ./.libs/libgstgl-1.0.so: error: undefined reference to 'vc_dispmanx_update_start'
| ./.libs/libgstgl-1.0.so: error: undefined reference to 'vc_dispmanx_element_change_attributes'
| ./.libs/libgstgl-1.0.so: error: undefined reference to 'vc_dispmanx_update_submit_sync'
| ./.libs/libgstgl-1.0.so: error: undefined reference to 'vc_dispmanx_element_add'
| ./.libs/libgstgl-1.0.so: error: undefined reference to 'vc_dispmanx_element_remove'
| ./.libs/libgstgl-1.0.so: error: undefined reference to 'vc_dispmanx_display_close'
| ./.libs/libgstgl-1.0.so: error: undefined reference to 'vc_dispmanx_display_open'
| collect2: error: ld returned 1 exit status
| gst-plugins-bad-1.10.4/gst-libs/gst/gl/gstglapi.h:36: Warning: GstGL: symbol='GL_GLEXT_PROTOTYPES': Unknown namespace for symbol 'GL_GLEXT_PROTOTYPES'
| linking of temporary binary failed: Command '['../../../arm-webos-linux-gnueabi-libtool', '--mode=link', '--tag=CC', 'arm-webos-linux-gnueabi-gcc', '-

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>