maliit: drop raspberrypi2 specific maliit-env
* using raspberrypi2 directory causes maliit-framework-qt5 (and
  everything which depends on it) to be effectively MACHINE_ARCH

* the only difference is added QT_QPA_PLATFORM=wayland and removed
  XDG_RUNTIME_DIR=/tmp/luna-session, if we really need this, then
  we should apply the same for all rpi MACHINEs

  OE qemux86@luneos ~/build/luneos-master/webos-ports $ diff -uNr meta-rpi-luneos/recipes-qt/maliit/files/raspberrypi2/maliit-env.conf meta-webos-ports/meta-luneos/recipes-qt/maliit/maliit-framework-qt5/maliit-env.conf
  --- meta-rpi-luneos/recipes-qt/maliit/files/raspberrypi2/maliit-env.conf        2016-04-06 09:45:28.440181147 +0000
  +++ meta-webos-ports/meta-luneos/recipes-qt/maliit/maliit-framework-qt5/maliit-env.conf 2018-12-09 09:32:30.258527881 +0000
  @@ -1,3 +1,3 @@
   LANGUAGE=en_US
  -QT_QPA_PLATFORM=wayland
   HOME=/var/lib/maliit
  +XDG_RUNTIME_DIR=/tmp/luna-session
  OE qemux86@luneos ~/build/luneos-master/webos-ports $ find meta-rpi-luneos/recipes-qt/maliit/
  meta-rpi-luneos/recipes-qt/maliit/
  meta-rpi-luneos/recipes-qt/maliit/files
  meta-rpi-luneos/recipes-qt/maliit/files/raspberrypi2
  meta-rpi-luneos/recipes-qt/maliit/files/raspberrypi2/maliit-env.conf
  meta-rpi-luneos/recipes-qt/maliit/maliit-framework-qt5_git.bbappend
  OE qemux86@luneos ~/build/luneos-master/webos-ports $ cat meta-rpi-luneos/recipes-qt/maliit/maliit-framework-qt5_git.bbappend
  FILESEXTRAPATHS_prepend_rpi := "${THISDIR}/files:"

* fixes:
  $ bitbake-diffsigs tmp-glibc/sstate-diff/1555495762/r*/*/maliit-framework-qt5/*do_fetch*
  NOTE: Starting bitbake server...
  Task dependencies changed from:
  ['ABIEXTENSION', 'ARMPKGARCH', 'ARMPKGARCH_tune-cortexa7thf-neon-vfpv4', 'ARMPKGSFX_DSP', 'ARMPKGSFX_EABI', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_FPU', 'ARMPKGSFX_THUMB', 'ARM_INSTRUCTION_SET', 'ARM_M_OPT', 'ARM_THUMB_OPT', 'ARM_THUMB_SUFFIX', 'DEFAULTTUNE', 'EXTENDPE', 'LIBCEXTENSION', 'MACHINE', 'MACHINE_ARCH', 'MULTIMACH_TARGET_SYS', 'PACKAGE_ARCH', 'PE', 'PN', 'PR', 'PV', 'SRCREV', 'SRC_URI', 'STAMP', 'TARGET_OS', 'TARGET_VENDOR', 'TUNE_CCARGS_MFLOAT', 'TUNE_CCARGS_MFPU', 'TUNE_FEATURES', 'TUNE_FEATURES_tune-cortexa7', 'TUNE_FEATURES_tune-cortexa7-neon', 'TUNE_FEATURES_tune-cortexa7-neon-vfpv4', 'TUNE_FEATURES_tune-cortexa7t-neon-vfpv4', 'TUNE_FEATURES_tune-cortexa7thf-neon-vfpv4', 'TUNE_PKGARCH', 'base_do_fetch', 'clean_recipe_sysroot']
  to:
  ['ABIEXTENSION', 'ARMPKGARCH', 'ARMPKGARCH_tune-cortexa7thf-neon-vfpv4', 'ARMPKGSFX_DSP', 'ARMPKGSFX_EABI', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_FPU', 'ARMPKGSFX_THUMB', 'ARM_INSTRUCTION_SET', 'ARM_M_OPT', 'ARM_THUMB_OPT', 'ARM_THUMB_SUFFIX', 'DEFAULTTUNE', 'EXTENDPE', 'LIBCEXTENSION', 'MULTIMACH_TARGET_SYS', 'PACKAGE_ARCH', 'PE', 'PN', 'PR', 'PV', 'SRCREV', 'SRC_URI', 'STAMP', 'TARGET_OS', 'TARGET_VENDOR', 'TUNE_CCARGS_MFLOAT', 'TUNE_CCARGS_MFPU', 'TUNE_FEATURES', 'TUNE_FEATURES_tune-cortexa7', 'TUNE_FEATURES_tune-cortexa7-neon', 'TUNE_FEATURES_tune-cortexa7-neon-vfpv4', 'TUNE_FEATURES_tune-cortexa7t-neon-vfpv4', 'TUNE_FEATURES_tune-cortexa7thf-neon-vfpv4', 'TUNE_PKGARCH', 'base_do_fetch', 'clean_recipe_sysroot']
  basehash changed from e59ec64d6e56d78108af2b6f9d35e08fe2ac10dcbb28c675517e8939b06fc2f1 to 1e4d4beb81fa0f2c4191a00d1fc0e03ea322786787d1a54633e6ad1061824de2
  List of dependencies for variable PACKAGE_ARCH changed from '{'MACHINE_ARCH'}' to '{'TUNE_PKGARCH'}'
  changed items: {'MACHINE_ARCH', 'TUNE_PKGARCH'}
  Dependency on Variable MACHINE was removed
  Dependency on Variable MACHINE_ARCH was removed
  Variable PACKAGE_ARCH value changed from '${MACHINE_ARCH}' to '${TUNE_PKGARCH}'
  Checksum for file maliit-env.conf changed from 1ebb78e71e65c4b4bdbfc26d1cd8707d to df5ef59e89be96ceaab9d7a2f861ed03

  === Comparing signatures for task do_configure.sigdata between raspberrypi2 and raspberrypi3 ===
  ERROR: maliit-framework-qt5 different signature for task do_configure.sigdata between raspberrypi2 and raspberrypi3
  NOTE: Starting bitbake server...
  Hash for dependent task maliit/maliit-framework-qt5_git.bb.do_generate_qt_config_file changed from b73824b6c70b2cff21173afc6932b3bb51744f422ae0bd5419f720a020641270 to 1107202903e9cf9d3c591681c07c44ed2e74cd9925fbe8f2da58555565e8c29a
  Unable to find matching sigdata for /OE/build/luneos-master/webos-ports/meta-qt5/recipes-qt/maliit/maliit-framework-qt5_git.bb.do_generate_qt_config_file with hashes b73824b6c70b2cff21173afc6932b3bb51744f422ae0bd5419f720a020641270 or 1107202903e9cf9d3c591681c07c44ed2e74cd9925fbe8f2da58555565e8c29a

  ERROR: webos-keyboard different signature for task do_configure.sigdata between raspberrypi2 and raspberrypi3
  NOTE: Starting bitbake server...
  Hash for dependent task webos-keyboard/webos-keyboard.bb.do_prepare_recipe_sysroot changed from ef2ff9716559a38e6359c284a55fd5360676a35998ded89a36fb549162dccb9c to fefc36119afe53e7392da37108c8ccd4fcb4c1f4b414479970bee90d4a1b4e6c
  Unable to find matching sigdata for /OE/build/luneos-master/webos-ports/meta-webos-ports/meta-luneos/recipes-luneos/webos-keyboard/webos-keyboard.bb.do_prepare_recipe_sysroot with hashes ef2ff9716559a38e6359c284a55fd5360676a35998ded89a36fb549162dccb9c or fefc36119afe53e7392da37108c8ccd4fcb4c1f4b414479970bee90d4a1b4e6c

  ERROR: 2 errors found in /OE/build/luneos-master/webos-ports/tmp-glibc/sstate-diff/1555495762/signatures.raspberrypi3.do_configure.sigdata.log

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>