qtbase: drop useless bbappend
* and drop QT_PACKAGES_ARCH as all packages using qt weren't using this variable anyway
  as detected in:
  http://jenkins.nas-admin.org/view/luneos-testing/job/luneos-testing_workspace-compare-signatures/14/consoleFull e.g.
  ERROR: fingerterm different signature for task do_configure.sigdata between raspberrypi2 and raspberrypi3
  runtaskdeps changed:
  apps/fingerterm.bb.do_prepare_recipe_sysroot with hash eddcbc5ef646c0366b5ac6e09992f760
   changed to
  apps/fingerterm.bb.do_prepare_recipe_sysroot with hash 122aac5248dea96b3df98c1e9125badf
  Hash for dependent task apps/fingerterm.bb.do_prepare_recipe_sysroot changed from eddcbc5ef646c0366b5ac6e09992f760 to 122aac5248dea96b3df98c1e9125badf

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>